







//------------------------------------------------------------------------------
// <auto-generated>
// Data access layer code generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System.CodeDom.Compiler;

namespace StyleCopPlus.Test.Helpers
{
    [GeneratedCode("TestHelperGenerator", "1.0")]
    public static partial class DataHelper
    {
public const string CheckParametersConstructorParameter = "CheckParameters.ConstructorParameter.cs";
        public const string CheckParametersConstructorParameterGold = "CheckParameters.ConstructorParameterGold.cs";
        public const string CheckParametersGenericParameter = "CheckParameters.GenericParameter.cs";
        public const string CheckParametersGenericParameterGold = "CheckParameters.GenericParameterGold.cs";
        public const string CheckParametersOutParameter = "CheckParameters.OutParameter.cs";
        public const string CheckParametersReferenceParameter = "CheckParameters.ReferenceParameter.cs";
        public const string CheckParametersReferenceParameterGold = "CheckParameters.ReferenceParameterGold.cs";
        public const string CheckParametersRefParameter = "CheckParameters.RefParameter.cs";
        public const string CheckParametersValueTypeParameter = "CheckParameters.ValueTypeParameter.cs";
        public const string CreateVariableConstructorCall = "CreateVariable.ConstructorCall.cs";
        public const string CreateVariableConstructorCallGold = "CreateVariable.ConstructorCallGold.cs";
        public const string CreateVariableConstructorCallGoldTyped = "CreateVariable.ConstructorCallGoldTyped.cs";
        public const string CreateVariableFluentApiCalls = "CreateVariable.FluentApiCalls.cs";
        public const string CreateVariableFluentApiCallsGold = "CreateVariable.FluentApiCallsGold.cs";
        public const string CreateVariableFluentApiCallsGoldTyped = "CreateVariable.FluentApiCallsGoldTyped.cs";
        public const string CreateVariablePropertyCall = "CreateVariable.PropertyCall.cs";
        public const string CreateVariablePropertyCallGold = "CreateVariable.PropertyCallGold.cs";
        public const string CreateVariablePropertyCallGoldTyped = "CreateVariable.PropertyCallGoldTyped.cs";
        public const string CreateVariableStaticCall = "CreateVariable.StaticCall.cs";
        public const string CreateVariableStaticCallGold = "CreateVariable.StaticCallGold.cs";
        public const string CreateVariableStaticCallGoldTyped = "CreateVariable.StaticCallGoldTyped.cs";
        public const string CreateVariableVoidCall = "CreateVariable.VoidCall.cs";
        public const string IntroduceFieldReadonlyField = "IntroduceField.ReadonlyField.cs";
        public const string IntroduceFieldReadonlyFieldGold = "IntroduceField.ReadonlyFieldGold.cs";
        public const string SP1001ThrowExpression = "SP1001.ThrowExpression.cs";
        public const string SP1001ThrowStatement = "SP1001.ThrowStatement.cs";
        public const string SP1001ThrowWithoutMessage = "SP1001.ThrowWithoutMessage.cs";
        public const string SP1001ValidThrowExpression = "SP1001.ValidThrowExpression.cs";
        public const string SP1001ValidThrowStatement = "SP1001.ValidThrowStatement.cs";
        public const string SP1002InvalidParameterName = "SP1002.InvalidParameterName.cs";
        public const string SP1002ValidParameterName = "SP1002.ValidParameterName.cs";
        public const string SP1131CorrectOperandsWithStatic = "SP1131.CorrectOperandsWithStatic.cs";
        public const string SP1131IncorrectOperands = "SP1131.IncorrectOperands.cs";
        public const string SP1131IncorrectOperandsFixed = "SP1131.IncorrectOperandsFixed.cs";
        public const string SP1131IncorrectOperandsWithConst = "SP1131.IncorrectOperandsWithConst.cs";
        public const string SP1131IncorrectOperandsWithConstFixed = "SP1131.IncorrectOperandsWithConstFixed.cs";
        public const string SP1131InvertedOperands = "SP1131.InvertedOperands.cs";
        public const string SP1131InvertedOperandsFixed = "SP1131.InvertedOperandsFixed.cs";
        public const string SP1131NotEqualsOperator = "SP1131.NotEqualsOperator.cs";
        public const string SP1131NotEqualsOperatorFixed = "SP1131.NotEqualsOperatorFixed.cs";
        public const string SP1131OperandWithinLambda = "SP1131.OperandWithinLambda.cs";
        public const string SP2100All = "SP2100.All.cs";
        public const string SP2100ConstructorDefinition = "SP2100.ConstructorDefinition.cs";
        public const string SP2100ConstructorDefinitionFixed = "SP2100.ConstructorDefinitionFixed.cs";
        public const string SP2100ConstructorInvocation = "SP2100.ConstructorInvocation.cs";
        public const string SP2100ConstructorInvocationFixed = "SP2100.ConstructorInvocationFixed.cs";
        public const string SP2100FluentApi = "SP2100.FluentApi.cs";
        public const string SP2100FluentApiFixed = "SP2100.FluentApiFixed.cs";
        public const string SP2100MethodDefinition = "SP2100.MethodDefinition.cs";
        public const string SP2100MethodDefinitionFixed = "SP2100.MethodDefinitionFixed.cs";
        public const string SP2100MethodInvocation = "SP2100.MethodInvocation.cs";
        public const string SP2100MethodInvocationFixed = "SP2100.MethodInvocationFixed.cs";
        public const string SP2100MethodInvocationWithAssignment = "SP2100.MethodInvocationWithAssignment.cs";
        public const string SP2100MethodInvocationWithAssignmentFixed = "SP2100.MethodInvocationWithAssignmentFixed.cs";
        public const string SP2101LongConstructor = "SP2101.LongConstructor.cs";
        public const string SP2101LongFinalizer = "SP2101.LongFinalizer.cs";
        public const string SP2101LongMethod = "SP2101.LongMethod.cs";
        public const string SP2101LongStaticConstructor = "SP2101.LongStaticConstructor.cs";
        public const string SP2101ValidClass = "SP2101.ValidClass.cs";
        public const string SP2102LongGetter = "SP2102.LongGetter.cs";
        public const string SP2102LongSetter = "SP2102.LongSetter.cs";
        public const string SP2102ValidClass = "SP2102.ValidClass.cs";
        public const string SP2103LongClass = "SP2103.LongClass.cs";
        public const string SP2103ValidClass = "SP2103.ValidClass.cs";

    }
}
