image: Visual Studio 2015

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /v:m