image: Visual Studio 2022

branches:
  only:
    - master

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - choco install opencover.portable
  - choco install codecov

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --configuration=Debug .\src\StyleCopPlus.Test\StyleCopPlus.Test.csproj" -filter:"+[StyleCopPlus]* -[StyleCopPlus.Test]*" -output:".\StyleCopPlus_coverage.xml" -oldstyle
  - codecov -f "StyleCopPlus_coverage.xml"

after_build:
  - ps: Get-ChildItem .\src\StyleCopPlus\bin\Release\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

after_test:
  - ps: Vsix-PushArtifacts -path .\src\StyleCopPlus.Vsix\bin\Release\*.vsix | Vsix-PublishToGallery -path .\src\StyleCopPlus.Vsix\bin\Release\*.vsix