// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StyleCopPlus.Vsix
{
    static class Vsix
    {
        public const string Id = "StyleCopPlus..f472894e-d3a6-4fe0-a4fc-5d32dfd0e204";
        public const string Name = "StyleCopPlus";
        public const string Description = "A set of analyzers and refactorings based on StyleCopPlus project implemented with Roslyn engine.";
        public const string Language = "en-US";
        public const string Version = "1.4.3";
        public const string Author = "Sergey Rybalkin";
        public const string Tags = "StyleCopPlus";
    }
}
