name: Build and test analyzers

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore ./src/StyleCopPlus.Test/StyleCopPlus.Test.csproj

      - name: Build analyzer
        run: dotnet build ./src/StyleCopPlus.Test/StyleCopPlus.Test.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
