name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build analyzer
      run: dotnet build --configuration Release

    - name: Pack NuGet package
      run: dotnet pack --configuration Release

    - name: Publish NuGet package
      uses: nuget/nuget@v1
      with:
        command: push
        nuget-api-key: ${{ secrets.NUGET_API_KEY }} # Make sure to add your NuGet API key as a secret in your repository
        packages: '**/*.nupkg'
        source: https://api.nuget.org/v3/index.json